-- BeerMate Display Manager — initial schema.
--
-- Conventions:
--   * Timestamps are TEXT in RFC3339 UTC ('2026-07-24T09:00:00Z'). SQLite has no
--     native time type; storing a sortable, unambiguous string keeps comparisons
--     correct and makes the database directly readable during troubleshooting.
--   * Booleans are INTEGER 0/1.
--   * Free-form per-type settings live in *_json TEXT columns validated in Go,
--     so adding a slide type needs no schema change.

-- ---------------------------------------------------------------------------
-- Identity and access
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    username       TEXT    NOT NULL,
    username_lower TEXT    NOT NULL UNIQUE,
    display_name   TEXT    NOT NULL DEFAULT '',
    password_hash  TEXT    NOT NULL,
    -- 'admin'  full control including emergency publishing and user management
    -- 'editor' content and playlist, but may not publish emergency overrides
    -- 'viewer' read-only dashboard
    role           TEXT    NOT NULL DEFAULT 'admin'
                     CHECK (role IN ('admin','editor','viewer')),
    disabled       INTEGER NOT NULL DEFAULT 0 CHECK (disabled IN (0,1)),
    must_change_pw INTEGER NOT NULL DEFAULT 0 CHECK (must_change_pw IN (0,1)),
    last_login_at  TEXT,
    created_at     TEXT    NOT NULL,
    updated_at     TEXT    NOT NULL
);

CREATE TABLE sessions (
    -- Only the SHA-256 of the session token is stored. A database leak (or a
    -- backup copy) therefore cannot be replayed as a live session.
    token_hash   TEXT    PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    csrf_secret  TEXT    NOT NULL,
    created_at   TEXT    NOT NULL,
    last_seen_at TEXT    NOT NULL,
    absolute_exp TEXT    NOT NULL,
    ip           TEXT    NOT NULL DEFAULT '',
    user_agent   TEXT    NOT NULL DEFAULT '',
    revoked_at   TEXT
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_exp  ON sessions(absolute_exp);

-- Login throttling state. Keyed by the throttle subject (IP or username) so a
-- single table serves both the per-IP and per-account buckets.
CREATE TABLE login_attempts (
    subject      TEXT    PRIMARY KEY,
    failures     INTEGER NOT NULL DEFAULT 0,
    first_fail   TEXT    NOT NULL,
    last_fail    TEXT    NOT NULL,
    locked_until TEXT
);

CREATE TABLE audit_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at  TEXT    NOT NULL,
    actor_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
    actor_name  TEXT    NOT NULL DEFAULT '',
    action      TEXT    NOT NULL,
    target_type TEXT    NOT NULL DEFAULT '',
    target_id   TEXT    NOT NULL DEFAULT '',
    detail      TEXT    NOT NULL DEFAULT '',
    ip          TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX idx_audit_created ON audit_log(created_at DESC);
CREATE INDEX idx_audit_action  ON audit_log(action, created_at DESC);

-- ---------------------------------------------------------------------------
-- Settings and secrets
-- ---------------------------------------------------------------------------

CREATE TABLE settings (
    key        TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL DEFAULT ''
);

-- Encrypted third-party credentials (social API tokens, KPI endpoint auth).
-- Ciphertext is AES-256-GCM under the key in /etc/beermate-display-manager/secret.key.
-- Plaintext never touches this table and never leaves the server process.
CREATE TABLE credentials (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL UNIQUE,
    kind        TEXT    NOT NULL DEFAULT 'bearer',
    ciphertext  BLOB    NOT NULL,
    nonce       BLOB    NOT NULL,
    hint        TEXT    NOT NULL DEFAULT '',   -- e.g. last 4 chars, for the UI only
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
);

-- ---------------------------------------------------------------------------
-- Media library
-- ---------------------------------------------------------------------------

CREATE TABLE media (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind          TEXT    NOT NULL CHECK (kind IN ('image','video','pdf','pdf_page')),
    -- stored_name is generated by the server; the client-supplied filename is
    -- kept only as display metadata and is never used to build a path.
    stored_name   TEXT    NOT NULL UNIQUE,
    original_name TEXT    NOT NULL DEFAULT '',
    mime          TEXT    NOT NULL,
    bytes         INTEGER NOT NULL,
    width         INTEGER NOT NULL DEFAULT 0,
    height        INTEGER NOT NULL DEFAULT 0,
    duration_ms   INTEGER NOT NULL DEFAULT 0,
    sha256        TEXT    NOT NULL,
    thumb_name    TEXT    NOT NULL DEFAULT '',
    poster_id     INTEGER REFERENCES media(id) ON DELETE SET NULL,
    parent_id     INTEGER REFERENCES media(id) ON DELETE CASCADE, -- pdf_page -> pdf
    page_number   INTEGER NOT NULL DEFAULT 0,
    warning       TEXT    NOT NULL DEFAULT '',   -- e.g. unverified codec
    created_at    TEXT    NOT NULL,
    created_by    TEXT    NOT NULL DEFAULT '',
    updated_at    TEXT    NOT NULL
);
CREATE INDEX idx_media_kind    ON media(kind, created_at DESC);
CREATE INDEX idx_media_parent  ON media(parent_id, page_number);
CREATE INDEX idx_media_sha     ON media(sha256);

-- ---------------------------------------------------------------------------
-- Websites and managed browser sessions
-- ---------------------------------------------------------------------------

CREATE TABLE websites (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    name              TEXT    NOT NULL,
    url               TEXT    NOT NULL,
    -- 'iframe'  embed directly in the player (cheap, needs a permissive site)
    -- 'managed' render in the CDP-driven Chromium and stream screenshots
    render_mode       TEXT    NOT NULL DEFAULT 'iframe'
                        CHECK (render_mode IN ('iframe','managed')),
    requires_auth     INTEGER NOT NULL DEFAULT 0 CHECK (requires_auth IN (0,1)),
    profile_id        TEXT    NOT NULL DEFAULT 'default',
    -- Session lifecycle for authenticated sites.
    session_state     TEXT    NOT NULL DEFAULT 'none'
                        CHECK (session_state IN
                          ('none','preparing','active','expired','reauth_required','error')),
    login_url_pattern TEXT    NOT NULL DEFAULT '',
    zoom              REAL    NOT NULL DEFAULT 1.0,
    capture_interval_ms INTEGER NOT NULL DEFAULT 5000,
    load_timeout_ms   INTEGER NOT NULL DEFAULT 20000,
    refresh_on_show   INTEGER NOT NULL DEFAULT 1 CHECK (refresh_on_show IN (0,1)),
    periodic_refresh_ms INTEGER NOT NULL DEFAULT 0,
    allow_insecure    INTEGER NOT NULL DEFAULT 0 CHECK (allow_insecure IN (0,1)),
    fallback_scene_id INTEGER,
    last_ok_at        TEXT,
    last_validated_at TEXT,
    last_login_at     TEXT,
    last_error        TEXT    NOT NULL DEFAULT '',
    created_at        TEXT    NOT NULL,
    updated_at        TEXT    NOT NULL,
    created_by        TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX idx_websites_state ON websites(session_state);

-- ---------------------------------------------------------------------------
-- Social feeds
-- ---------------------------------------------------------------------------

CREATE TABLE social_feeds (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    name           TEXT    NOT NULL,
    platform       TEXT    NOT NULL,   -- rss | atom | json | youtube | webhook | manual | ...
    source         TEXT    NOT NULL DEFAULT '',
    config_json    TEXT    NOT NULL DEFAULT '{}',
    credential_id  INTEGER REFERENCES credentials(id) ON DELETE SET NULL,
    enabled        INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
    refresh_sec    INTEGER NOT NULL DEFAULT 900,
    max_items      INTEGER NOT NULL DEFAULT 20,
    include_media  INTEGER NOT NULL DEFAULT 1 CHECK (include_media IN (0,1)),
    include_text   INTEGER NOT NULL DEFAULT 1 CHECK (include_text IN (0,1)),
    -- 'manual' (default, recommended) holds posts for approval before display.
    moderation     TEXT    NOT NULL DEFAULT 'manual'
                     CHECK (moderation IN ('manual','auto')),
    hashtag_filter TEXT    NOT NULL DEFAULT '',
    keyword_filter TEXT    NOT NULL DEFAULT '',
    blocklist      TEXT    NOT NULL DEFAULT '',
    active_from    TEXT,
    active_until   TEXT,
    template       TEXT    NOT NULL DEFAULT 'cards',
    connection_state TEXT  NOT NULL DEFAULT 'idle'
                     CHECK (connection_state IN ('idle','ok','error','unauthorised','rate_limited')),
    last_refresh_at TEXT,
    last_error     TEXT    NOT NULL DEFAULT '',
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TEXT,
    created_at     TEXT    NOT NULL,
    updated_at     TEXT    NOT NULL
);
CREATE INDEX idx_feeds_enabled ON social_feeds(enabled, next_attempt_at);

CREATE TABLE social_posts (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    feed_id       INTEGER NOT NULL REFERENCES social_feeds(id) ON DELETE CASCADE,
    external_id   TEXT    NOT NULL,
    author        TEXT    NOT NULL DEFAULT '',
    author_handle TEXT    NOT NULL DEFAULT '',
    avatar_url    TEXT    NOT NULL DEFAULT '',
    text          TEXT    NOT NULL DEFAULT '',
    media_url     TEXT    NOT NULL DEFAULT '',
    media_kind    TEXT    NOT NULL DEFAULT '',
    permalink     TEXT    NOT NULL DEFAULT '',
    posted_at     TEXT,
    fetched_at    TEXT    NOT NULL,
    moderation_state TEXT NOT NULL DEFAULT 'pending'
                     CHECK (moderation_state IN ('pending','approved','rejected','hidden')),
    pinned        INTEGER NOT NULL DEFAULT 0 CHECK (pinned IN (0,1)),
    moderated_by  TEXT    NOT NULL DEFAULT '',
    moderated_at  TEXT,
    UNIQUE (feed_id, external_id)
);
CREATE INDEX idx_posts_feed_state ON social_posts(feed_id, moderation_state, posted_at DESC);
CREATE INDEX idx_posts_fetched    ON social_posts(feed_id, fetched_at);

-- ---------------------------------------------------------------------------
-- Playlist: revisions -> scenes -> zones
-- ---------------------------------------------------------------------------

-- Exactly one revision has is_draft = 1 at any time. Editing mutates the draft;
-- publishing stamps published_at on it and clones a fresh draft. The player only
-- ever reads a published revision, so a half-finished edit can never go live.
CREATE TABLE playlist_revisions (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    is_draft     INTEGER NOT NULL DEFAULT 1 CHECK (is_draft IN (0,1)),
    published_at TEXT,
    created_at   TEXT    NOT NULL,
    created_by   TEXT    NOT NULL DEFAULT '',
    published_by TEXT    NOT NULL DEFAULT '',
    note         TEXT    NOT NULL DEFAULT '',
    parent_id    INTEGER REFERENCES playlist_revisions(id) ON DELETE SET NULL
);
CREATE INDEX idx_rev_published ON playlist_revisions(published_at DESC);
-- Enforce the single-draft invariant at the storage layer, not just in Go.
CREATE UNIQUE INDEX idx_rev_single_draft ON playlist_revisions(is_draft) WHERE is_draft = 1;

CREATE TABLE scenes (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    revision_id INTEGER NOT NULL REFERENCES playlist_revisions(id) ON DELETE CASCADE,
    -- stable_id survives publish/clone so history and "same scene" comparisons work.
    stable_id   TEXT    NOT NULL,
    name        TEXT    NOT NULL,
    position    INTEGER NOT NULL DEFAULT 0,
    enabled     INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
    layout      TEXT    NOT NULL DEFAULT 'fullscreen',
    layout_json TEXT    NOT NULL DEFAULT '{}',   -- custom_grid definition
    duration_ms INTEGER NOT NULL DEFAULT 60000,
    background  TEXT    NOT NULL DEFAULT '',
    transition  TEXT    NOT NULL DEFAULT 'fade',
    active_from TEXT,
    active_until TEXT,
    -- Bit 0 = Monday .. bit 6 = Sunday. 127 = every day.
    days_mask   INTEGER NOT NULL DEFAULT 127,
    valid       INTEGER NOT NULL DEFAULT 1 CHECK (valid IN (0,1)),
    validation_msg TEXT NOT NULL DEFAULT '',
    last_played_at TEXT,
    last_error     TEXT NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL,
    created_by  TEXT    NOT NULL DEFAULT '',
    updated_at  TEXT    NOT NULL,
    updated_by  TEXT    NOT NULL DEFAULT '',
    UNIQUE (revision_id, stable_id)
);
CREATE INDEX idx_scenes_rev ON scenes(revision_id, position);

CREATE TABLE zones (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    scene_id     INTEGER NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
    slot         TEXT    NOT NULL,          -- 'a','b','c','d' — layout slot name
    -- Geometry as percentages of the screen, resolved from the layout template
    -- but overridable for custom_grid.
    x            REAL    NOT NULL DEFAULT 0,
    y            REAL    NOT NULL DEFAULT 0,
    w            REAL    NOT NULL DEFAULT 100,
    h            REAL    NOT NULL DEFAULT 100,
    z            INTEGER NOT NULL DEFAULT 0,
    content_type TEXT    NOT NULL DEFAULT 'empty',
    content_ref  TEXT    NOT NULL DEFAULT '',  -- media id, website id, feed id...
    config_json  TEXT    NOT NULL DEFAULT '{}',
    style_json   TEXT    NOT NULL DEFAULT '{}',
    label        TEXT    NOT NULL DEFAULT '',
    UNIQUE (scene_id, slot)
);
CREATE INDEX idx_zones_scene ON zones(scene_id);

-- ---------------------------------------------------------------------------
-- Scheduling
-- ---------------------------------------------------------------------------

CREATE TABLE schedule_rules (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    -- 'weekly' uses weekday; 'date' uses on_date (a one-off / holiday override).
    kind     TEXT    NOT NULL CHECK (kind IN ('weekly','date')),
    weekday  INTEGER,          -- 0=Monday .. 6=Sunday
    on_date  TEXT,             -- 'YYYY-MM-DD'
    enabled  INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
    -- NULL on_time/off_time with enabled=1 means "display off all day".
    on_time  TEXT,             -- 'HH:MM'
    off_time TEXT,             -- 'HH:MM'
    label    TEXT    NOT NULL DEFAULT '',
    created_at TEXT  NOT NULL,
    updated_at TEXT  NOT NULL
);
CREATE UNIQUE INDEX idx_sched_weekday ON schedule_rules(weekday) WHERE kind = 'weekly';
CREATE UNIQUE INDEX idx_sched_date    ON schedule_rules(on_date) WHERE kind = 'date';

-- A temporary manual wake/sleep that expires on its own so an operator cannot
-- accidentally leave the screen on overnight.
CREATE TABLE schedule_overrides (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    mode       TEXT    NOT NULL CHECK (mode IN ('wake','sleep')),
    starts_at  TEXT    NOT NULL,
    expires_at TEXT    NOT NULL,
    created_by TEXT    NOT NULL DEFAULT '',
    created_at TEXT    NOT NULL,
    cleared_at TEXT
);
CREATE INDEX idx_override_active ON schedule_overrides(cleared_at, expires_at);

-- ---------------------------------------------------------------------------
-- Emergency / priority messages
-- ---------------------------------------------------------------------------

CREATE TABLE emergency_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    heading     TEXT    NOT NULL,
    body        TEXT    NOT NULL DEFAULT '',
    severity    TEXT    NOT NULL DEFAULT 'info'
                  CHECK (severity IN ('info','warning','critical')),
    starts_at   TEXT    NOT NULL,
    expires_at  TEXT    NOT NULL,
    dismissed_at TEXT,
    created_by  TEXT    NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL
);
CREATE INDEX idx_emergency_window ON emergency_messages(dismissed_at, starts_at, expires_at);

-- ---------------------------------------------------------------------------
-- Player state and backups
-- ---------------------------------------------------------------------------

-- Single-row table (id = 1) holding the last reported player status.
CREATE TABLE player_state (
    id             INTEGER PRIMARY KEY CHECK (id = 1),
    online         INTEGER NOT NULL DEFAULT 0 CHECK (online IN (0,1)),
    last_heartbeat TEXT,
    revision_id    INTEGER,
    current_scene  TEXT    NOT NULL DEFAULT '',
    current_slide  TEXT    NOT NULL DEFAULT '',
    browser_ua     TEXT    NOT NULL DEFAULT '',
    detail_json    TEXT    NOT NULL DEFAULT '{}',
    last_error     TEXT    NOT NULL DEFAULT '',
    updated_at     TEXT    NOT NULL
);
INSERT INTO player_state (id, online, updated_at)
VALUES (1, 0, strftime('%Y-%m-%dT%H:%M:%SZ','now'));

CREATE TABLE backups (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    filename   TEXT    NOT NULL UNIQUE,
    bytes      INTEGER NOT NULL,
    sha256     TEXT    NOT NULL,
    kind       TEXT    NOT NULL DEFAULT 'manual'
                 CHECK (kind IN ('manual','pre_change','pre_restore','scheduled')),
    note       TEXT    NOT NULL DEFAULT '',
    created_at TEXT    NOT NULL,
    created_by TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX idx_backups_created ON backups(created_at DESC);

-- ---------------------------------------------------------------------------
-- Seed: the initial draft revision and the legacy 08:00-17:00 daily schedule
-- ---------------------------------------------------------------------------

INSERT INTO playlist_revisions (id, is_draft, created_at, created_by, note)
VALUES (1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), 'system', 'initial draft');

INSERT INTO schedule_rules (kind, weekday, enabled, on_time, off_time, label, created_at, updated_at)
SELECT 'weekly', d.wd, 1, '08:00', '17:00', '',
       strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now')
FROM (SELECT 0 AS wd UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
      UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) AS d;
